// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type AnalysisResult struct {
	ID              int32              `json:"id"`
	ExperimentID    string             `json:"experiment_id"`
	Severity        string             `json:"severity"`
	RootCause       string             `json:"root_cause"`
	Confidence      float64            `json:"confidence"`
	Recommendations json.RawMessage    `json:"recommendations"`
	ResilienceScore pgtype.Float8      `json:"resilience_score"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Experiment struct {
	ID              string             `json:"id"`
	Config          json.RawMessage    `json:"config"`
	Status          string             `json:"status"`
	Phase           string             `json:"phase"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	SteadyState     []byte             `json:"steady_state"`
	Hypothesis      pgtype.Text        `json:"hypothesis"`
	InjectionResult []byte             `json:"injection_result"`
	Observations    []byte             `json:"observations"`
	RollbackResult  []byte             `json:"rollback_result"`
	Error           pgtype.Text        `json:"error"`
	AiInsights      []byte             `json:"ai_insights"`
}

type ProbeResult struct {
	ID           int32              `json:"id"`
	ExperimentID string             `json:"experiment_id"`
	ProbeType    string             `json:"probe_type"`
	Mode         string             `json:"mode"`
	Result       json.RawMessage    `json:"result"`
	Passed       bool               `json:"passed"`
	ExecutedAt   pgtype.Timestamptz `json:"executed_at"`
}

type Snapshot struct {
	ID           int32              `json:"id"`
	ExperimentID string             `json:"experiment_id"`
	Type         string             `json:"type"`
	Namespace    pgtype.Text        `json:"namespace"`
	Data         json.RawMessage    `json:"data"`
	CapturedAt   pgtype.Timestamptz `json:"captured_at"`
}
