// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snapshots.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO snapshots (experiment_id, type, namespace, data, captured_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, experiment_id, type, namespace, data, captured_at
`

type CreateSnapshotParams struct {
	ExperimentID string             `json:"experiment_id"`
	Type         string             `json:"type"`
	Namespace    pgtype.Text        `json:"namespace"`
	Data         json.RawMessage    `json:"data"`
	CapturedAt   pgtype.Timestamptz `json:"captured_at"`
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRow(ctx, createSnapshot,
		arg.ExperimentID,
		arg.Type,
		arg.Namespace,
		arg.Data,
		arg.CapturedAt,
	)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.Type,
		&i.Namespace,
		&i.Data,
		&i.CapturedAt,
	)
	return i, err
}

const getSnapshotsByExperiment = `-- name: GetSnapshotsByExperiment :many
SELECT id, experiment_id, type, namespace, data, captured_at FROM snapshots WHERE experiment_id = $1 ORDER BY captured_at DESC
`

func (q *Queries) GetSnapshotsByExperiment(ctx context.Context, experimentID string) ([]Snapshot, error) {
	rows, err := q.db.Query(ctx, getSnapshotsByExperiment, experimentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snapshot{}
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.ExperimentID,
			&i.Type,
			&i.Namespace,
			&i.Data,
			&i.CapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
